SELECT *  
FROM HR.EMPLOYEES OEMP  
WHERE SALARY = ( 
                    SELECT MAX(SALARY)  
                    FROM HR.EMPLOYEES IEMP  
                    WHERE IEMP.DEPARTMENT_ID = OEMP.DEPARTMENT_ID 
                );

SELECT * FROM HR.EMPLOYEES OEMP WHERE 1=(SELECT COUNT(*) FROM HR.EMPLOYEES IEMP WHERE IEMP.SALARY>OEMP.SALARY);                
