SELECT * 
FROM HR.EMPLOYEES WHERE SALARY BETWEEN 10000 AND 17000;

SELECT * 
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM HR.EMPLOYEES WHERE FIRST_NAME='Alexander');

SELECT * 
FROM HR.EMPLOYEES
WHERE PHONE_NUMBER LIKE '%.12_.%';

SELECT * 
FROM HR.EMPLOYEES
WHERE FIRST_NAME LIKE '%am';

SELECT FIRST_NAME,LOWER(FIRST_NAME)
FROM HR.EMPLOYEES 
WHERE DEPARTMENT_ID = 60;

SELECT MAX(SALARY)
FROM HR.EMPLOYEES 
WHERE DEPARTMENT_ID = 60;


SELECT CEIL(1000.1) FROM DUAL;
SELECT FLOOR(1000.9) FROM DUAL;
SELECT ROUND(1000.5) FROM DUAL;
SELECT POWER(3,2) FROM DUAL;

SELECT CHR(38) FROM DUAL;
SELECT CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME) FROM HR.EMPLOYEES;
SELECT FIRST_NAME||' '||LAST_NAME FROM HR.EMPLOYEES;

SELECT INITCAP('janaganamana adhinayaka jayahe') FROM DUAl;
SELECT LENGTH('jaihindh') FROM DUAL;
SELECT RPAD('jaihindh',10) FROM DUAL;

SELECT TRIM('    jaihindh   ') FROM DUAL;
SELECT CONCAT(FIRST_NAME,LAST_NAME) FROM HR.EMPLOYEES;

SELECT NLS_INITCAP('ijsland', 'NLS_SORT = XDutch')  FROM DUAL;

SELECT SUBSTR('Good Morning',0,4) FROM DUAL;
SELECT INSTR('Good Morning Good Night Good After Noon','Good',1,4) FROM DUAL;

SELECT TRANSLATE('Good Morning','oi','x!') FROM DUAL;

SELECT ADD_MONTHS(SYSDATE,2) FROM DUAL;
SELECT CURRENT_DATE FROM DUAL;
SELECT CURRENT_TIMESTAMP FROM DUAL;
SELECT SESSIONTIMEZONE FROM DUAL;
SELECT DBTIMEZONE FROM DUAL;
SELECT TO_CHAR(CURRENT_DATE,'ddTH')||' '||TRIM(TO_CHAR(CURRENT_DATE,'MONTH'))||' '||TO_CHAR(CURRENT_DATE,'YYYY') FROM DUAL;

SELECT ADD_MONTHS(TO_DATE('11 JUN 2022','DD MON YYYY'),1*12) FROM DUAL;
SELECT TO_CHAR(CURRENT_DATE,'MM/DD/YYYY') FROM DUAL;

SELECT TO_DATE('06/11/2022','DD/MM/YYYY') FROM DUAL;



