SELECT * 
FROM HR.EMPLOYEES 
WHERE DEPARTMENT_ID = 60 AND SALARY =  
        (
                SELECT 
                MAX(SALARY) 
                FROM HR.EMPLOYEES
                WHERE DEPARTMENT_ID=60
        );
        
        
SELECT DEPARTMENT_ID,count(*) as cnt 
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING count(*)>5
ORDER BY cnt DESC;    

SELECT DEPARTMENT_ID,MANAGER_ID,count(*) as cnt 
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID,MANAGER_ID
ORDER BY DEPARTMENT_ID;


SELECT DEPARTMENT_ID,MANAGER_ID,count(*) as cnt 
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID,MANAGER_ID
ORDER BY DEPARTMENT_ID;

CREATE TABLE TEST_DATA(
    test_id INTEGER,
    name VARCHAR(64)
);

CREATE SEQUENCE TEST_DATA_SEQ START WITH 3 INCREMENT BY 5;

INSERT INTO TEST_DATA (test_id,name) VALUES(TEST_DATA_SEQ.NEXTVAL,'Bala Gangadhar Thilak');
INSERT INTO TEST_DATA (test_id,name) VALUES(TEST_DATA_SEQ.NEXTVAL,'Alluri Seetha Ramaraju');
INSERT INTO TEST_DATA (test_id,name) VALUES(TEST_DATA_SEQ.NEXTVAL,'Jansi');

SELECT * FROM TEST_DATA;
SELECT TEST_DATA_SEQ.NEXTVAL FROM DUAL;
SELECT TEST_DATA_SEQ.CURRVAL FROM DUAL;

SELECT FIRST_NAME FROM HR.EMPLOYEES WHERE EMPLOYEE_ID IN(
    SELECT EMPLOYEE_ID 
    FROM HR.JOB_HISTORY
    WHERE JOB_ID='ST_CLERK'
);

    SELECT *
    FROM HR.JOB_HISTORY;
    
    
    SELECT * FROM HR.EMPLOYEES;
    
    SELECT JOB_ID FROM HR.JOB_HISTORY 
    WHERE START_DATE = '21-SEP-97' AND EMPLOYEE_ID = (SELECT EMPLOYEE_ID FROM HR.EMPLOYEES WHERE FIRST_NAME='Neena');

    SELECT JOB_ID FROM HR.JOB_HISTORY 
    WHERE START_DATE < '01-JAN-2002' AND END_DATE > '01-JAN-2002' AND EMPLOYEE_ID = (SELECT EMPLOYEE_ID FROM HR.EMPLOYEES WHERE FIRST_NAME='Neena');

    SELECT JOB_ID FROM HR.JOB_HISTORY 
    WHERE '01-JAN-2002' BETWEEN START_DATE AND END_DATE AND EMPLOYEE_ID = (SELECT EMPLOYEE_ID FROM HR.EMPLOYEES WHERE FIRST_NAME='Neena');

    SELECT * FROM HR.DEPARTMENTS;
    
    SELECT DEPARTMENT_NAME FROM HR.DEPARTMENTS WHERE DEPARTMENT_ID = 
    (
        SELECT DEPARTMENT_ID
        FROM HR.EMPLOYEES
        GROUP BY DEPARTMENT_ID
        HAVING COUNT(*) = 
                (
                    SELECT MAX(COUNT(*))
                    FROM HR.EMPLOYEES
                    GROUP BY DEPARTMENT_ID
                )
    );



