SELECT * FROM HR.LOCATIONS;
SELECT * FROM HR.COUNTRIES;
SELECT * FROM HR.REGIONS;
SELECT * FROM HR.EMPLOYEES;
SELECT * FROM HR.JOB_HISTORY;
SELECT * FROM HR.DEPARTMENTS;

SELECT * FROM SH.PRODUCTS WHERE PROD_ID=13;

SELECT * FROM SH.COSTS WHERE PROD_ID=13 ORDER BY TIME_ID;

SELECT * FROM SH.SALES WHERE PROD_ID=13;

SELECT * FROM SH.CHANNELS;


SELECT DEPARTMENT_ID,COUNT(*) 
FROM HR.EMPLOYEES
GROUP BY DEPARTMENT_ID
HAVING COUNT(*) = 
    (
        SELECT MAX(COUNT(*))
        FROM HR.EMPLOYEES
        GROUP BY DEPARTMENT_ID
    );
SELECT * FROM HR.DEPARTMENTS;    
SELECT * FROM HR.LOCATIONS;    

SELECT FIRST_NAME,DEPARTMENT_NAME,EMP.DEPARTMENT_ID
FROM HR.EMPLOYEES EMP,HR.DEPARTMENTS DEPT WHERE EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID;

SELECT *
FROM HR.EMPLOYEES EMP INNER JOIN HR.DEPARTMENTS DEPT ON EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID
                      INNER JOIN HR.LOCATIONS LOC ON DEPT.LOCATION_ID = LOC.LOCATION_ID;

SELECT FIRST_NAME
FROM HR.EMPLOYEES 
WHERE DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID FROM HR.DEPARTMENTS WHERE MANAGER_ID=201
);


SELECT LOCATION_ID,COUNT(*)
FROM HR.EMPLOYEES EMP INNER JOIN HR.DEPARTMENTS DEPT ON EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID
GROUP BY LOCATION_ID
HAVING COUNT(*) = (
    SELECT MAX(COUNT(*))
    FROM HR.EMPLOYEES EMP INNER JOIN HR.DEPARTMENTS DEPT ON EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID
    GROUP BY LOCATION_ID
);

SELECT COUNTRY_ID,COUNT(*)
FROM HR.EMPLOYEES EMP INNER JOIN HR.DEPARTMENTS DEPT ON EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID
                      INNER JOIN HR.LOCATIONS LOC ON DEPT.LOCATION_ID = LOC.LOCATION_ID
GROUP BY COUNTRY_ID
HAVING COUNT(*) = (
    SELECT MAX(COUNT(*))
    FROM HR.EMPLOYEES EMP INNER JOIN HR.DEPARTMENTS DEPT ON EMP.DEPARTMENT_ID=DEPT.DEPARTMENT_ID
                          INNER JOIN HR.LOCATIONS LOC ON DEPT.LOCATION_ID = LOC.LOCATION_ID
    GROUP BY COUNTRY_ID
);

