SELECT DEPARTMENT_NAME,COUNT(EMPLOYEE_ID)
FROM HR.EMPLOYEES EMP RIGHT OUTER JOIN HR.DEPARTMENTS DEPT ON EMP.DEPARTMENT_ID = DEPT.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME;


SELECT EMP.FIRST_NAME,MGR.FIRST_NAME 
FROM HR.EMPLOYEES EMP LEFT OUTER JOIN HR.EMPLOYEES MGR ON EMP.MANAGER_ID=MGR.EMPLOYEE_ID;


CREATE TABLE SALARY_BANDS(
    BANDNAME VARCHAR(20),
    MIN_SALARY NUMERIC(12,2),
    MAX_SALARY NUMERIC(12,2)
);

INSERT INTO SALARY_BANDS VALUES('A',0,5000);
INSERT INTO SALARY_BANDS VALUES('B',5001,15000);
INSERT INTO SALARY_BANDS VALUES('C',15001,25000);
INSERT INTO SALARY_BANDS VALUES('D',25001,50000);

SELECT * FROM SALARY_BANDS;

SELECT EMP.FIRST_NAME,EMP.SALARY,BAND.BANDNAME 
FROM HR.EMPLOYEES EMP INNER JOIN SALARY_BANDS BAND ON BAND.MIN_SALARY<= EMP.SALARY AND BAND.MAX_SALARY>=EMP.SALARY
ORDER BY EMP.SALARY DESC;

SELECT * FROM HR.EMPLOYEES;

SELECT DEPARTMENT_ID FROM HR.DEPARTMENTS
INTERSECT
SELECT DEPARTMENT_ID FROM HR.EMPLOYEES;





