SELECT * FROM STUDENTS;
SELECT * FROM BATCHES;
SELECT * FROM COURSES;
SELECT * FROM COURSE_DETAILS;
SELECT * FROM BATCH_DETAILS;
SELECT * FROM TECHNOLOGIES;

WITH 
bv1 AS (SELECT STUDENT_ID,BATCH_NAME FROM BATCH_DETAILS BD INNER JOIN BATCHES B ON BD.BATCH_ID=B.BATCH_ID WHERE COURSE_ID=1),
bv2 AS (SELECT STUDENT_ID,BATCH_NAME FROM BATCH_DETAILS BD INNER JOIN BATCHES B ON BD.BATCH_ID=B.BATCH_ID WHERE COURSE_ID=2)
SELECT STUDENT_NAME,BATCH_NAME FROM STUDENTS st INNER JOIN bv1 ON st.STUDENT_ID = bv1.STUDENT_ID;


CREATE VIEW CRS1 AS SELECT * FROM COURSE_DETAILS WHERE COURSE_ID=1 WITH CHECK OPTION;

SELECT * FROM CRS1;

INSERT INTO CRS1 VALUES(2,9,NULL,8);

CREATE VIEW BV1 AS SELECT STUDENT_ID,BATCH_NAME FROM BATCH_DETAILS BD INNER JOIN BATCHES B ON BD.BATCH_ID=B.BATCH_ID WHERE COURSE_ID=1

SELECT * FROM BV1;

INSERT INTO BV1 VALUES(2,'CLUSTER#2');

CREATE UNIQUE INDEX BNAME ON COURSES(COURSE_NAME);

DROP INDEX BNAME;

SELECT * FROM COURSES;

UPDATE COURSES SET COURSE_NAME='FULL_JAVA_ADV' WHERE COURSE_ID=6;

INSERT INTO COURSES VALUES(8,'FULL_UI',NULL);



