
CREATE OR REPLACE PROCEDURE PROC_EMP_NAME(P_EMPLOYEE_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE)
AS
    V_FIRST_NAME HR.EMPLOYEES.FIRST_NAME%TYPE;
    V_LAST_NAME HR.EMPLOYEES.LAST_NAME%TYPE;
BEGIN 
    SELECT FIRST_NAME,LAST_NAME
    INTO V_FIRST_NAME,V_LAST_NAME
    FROM HR.EMPLOYEES 
    WHERE EMPLOYEE_ID=P_EMPLOYEE_ID;
    
    DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME||'  '||V_LAST_NAME);
    
END;

EXEC PROC_EMP_NAME(101);

CREATE OR REPLACE FUNCTION FUN_EMP_NAME(P_EMPLOYEE_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE)
RETURN  HR.EMPLOYEES.FIRST_NAME%TYPE
AS
    V_EMP_NAME HR.EMPLOYEES.FIRST_NAME%TYPE;
BEGIN 
    SELECT FIRST_NAME
    INTO V_EMP_NAME
    FROM HR.EMPLOYEES 
    WHERE EMPLOYEE_ID=P_EMPLOYEE_ID;
    
    RETURN V_EMP_NAME;
END;

CREATE OR REPLACE PROCEDURE PROC_GET_DEPT_EMPS(P_DEPARTMENT_ID HR.EMPLOYEES.DEPARTMENT_ID%TYPE)
AS
    V_FIRST_NAME HR.EMPLOYEES.FIRST_NAME%TYPE;
    CURSOR CUR_EMP_NAMES IS SELECT FIRST_NAME FROM HR.EMPLOYEES WHERE DEPARTMENT_ID=P_DEPARTMENT_ID;
BEGIN 
       OPEN CUR_EMP_NAMES;
       LOOP
           FETCH CUR_EMP_NAMES INTO V_FIRST_NAME;
           EXIT WHEN CUR_EMP_NAMES%NOTFOUND;
           
           DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME);
       END LOOP;
       CLOSE CUR_EMP_NAMES;
END;

EXEC PROC_GET_DEPT_EMPS(90);
