CREATE OR REPLACE PROCEDURE GET_EMP_NAME(P_EMPLOYEE_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE)
AS
    EMP_NAME HR.EMPLOYEES.FIRST_NAME%TYPE;
BEGIN 
    SELECT FIRST_NAME INTO EMP_NAME
    FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID = P_EMPLOYEE_ID;
    
    DBMS_OUTPUT.PUT_LINE(EMP_NAME);
EXCEPTION    
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('No employee found with given id');
END;

CREATE OR REPLACE PROCEDURE GET_EMP_ID(P_EMPLOYEE_NAME HR.EMPLOYEES.FIRST_NAME%TYPE)
AS
    V_EMP_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE;
BEGIN 
    SELECT EMPLOYEE_ID INTO V_EMP_ID
    FROM HR.EMPLOYEES
    WHERE FIRST_NAME = P_EMPLOYEE_NAME;
    
    DBMS_OUTPUT.PUT_LINE(V_EMP_ID);
EXCEPTION 
    WHEN TOO_MANY_ROWS THEN
        DBMS_OUTPUT.PUT_LINE('Many employees exists with the given name');
END;


EXEC GET_EMP_NAME(80);

EXEC GET_EMP_ID('David');

SELECT FIRST_NAME FROM HR.EMPLOYEES 
GROUP BY FIRST_NAME
HAVING COUNT(*) > 1;

SELECT * FROM HR.EMPLOYEES WHERE FIRST_NAME='David';


CREATE TABLE NXTUSERS
(
    userid INTEGER PRIMARY KEY,
    username VARCHAR2(64),
    password VARCHAR2(256),
    CREATED DATE,
    CREATEDBY VARCHAR2(64)
);
-20999 to -20000
CREATE SEQUENCE SEQ_NXTUSERS;

CREATE OR REPLACE PROCEDURE CREATE_SYUSER(P_USERNAME NXTUSERS.USERNAME%TYPE,P_PASSWORD NXTUSERS.PASSWORD%TYPE)
AS
    INVALID_PASSWORD EXCEPTION;
    PRAGMA EXCEPTION_INIT(INVALID_PASSWORD,-20999);
BEGIN
    IF LENGTH(P_PASSWORD) >= 8 THEN
        INSERT INTO NXTUSERS VALUES(SEQ_NXTUSERS.nextval,P_USERNAME,P_PASSWORD,SYSDATE,USER);
    ELSE
        --RAISE INVALID_PASSWORD;
        RAISE_APPLICATION_ERROR('-20999','Password can not be shorter than 8 characters');
    END IF;
EXCEPTION
    WHEN INVALID_PASSWORD THEN
        DBMS_OUTPUT.PUT_LINE('Invalid Password');
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No Data Found');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE(SQLCODE);
        DBMS_OUTPUT.PUT_LINE(SQLERRM);
END;



EXEC CREATE_SYUSER('Vamsi','Vamsi');


SELECT * FROM NXTUSERS;
