CREATE OR REPLACE PACKAGE EMP_UTILS AS
    TYPE TYPE_EMP_DETAILS IS RECORD(
        EMPLOYEE_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE,
        EMPLOYEE_NAME HR.EMPLOYEES.FIRST_NAME%TYPE,
        SALARY HR.EMPLOYEES.SALARY%TYPE
    );
    PROCEDURE GET_EMP_BY_ID(P_EMPLOYEE_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE);
    PROCEDURE GET_MAX_SAL_OF_DEPT(P_DEPARTMENT_ID HR.EMPLOYEES.DEPARTMENT_ID%TYPE);
    FUNCTION  GET_EMP_DETAILS_BY_ID(P_EMPLOYEE_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE) RETURN TYPE_EMP_DETAILS;
    
END;

CREATE OR REPLACE PACKAGE BODY EMP_UTILS AS
    PROCEDURE GET_EMP_BY_ID(P_EMPLOYEE_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE)
    AS
        V_EMPLOYEE_NAME HR.EMPLOYEES.FIRST_NAME%TYPE;
    BEGIN
        SELECT FIRST_NAME INTO V_EMPLOYEE_NAME
        FROM HR.EMPLOYEES
        WHERE EMPLOYEE_ID = P_EMPLOYEE_ID;
        
        DBMS_OUTPUT.PUT_LINE(V_EMPLOYEE_NAME);
    END;

    PROCEDURE GET_MAX_SAL_OF_DEPT(P_DEPARTMENT_ID HR.EMPLOYEES.DEPARTMENT_ID%TYPE)
    AS
        V_TOTAL_SAL NUMERIC(12,2);
    BEGIN
        SELECT SUM(SALARY) INTO V_TOTAL_SAL
        FROM HR.EMPLOYEES
        WHERE DEPARTMENT_ID = P_DEPARTMENT_ID;
        
        DBMS_OUTPUT.PUT_LINE(V_TOTAL_SAL);
    END;
    
    FUNCTION  GET_EMP_DETAILS_BY_ID(P_EMPLOYEE_ID HR.EMPLOYEES.EMPLOYEE_ID%TYPE) RETURN TYPE_EMP_DETAILS
    AS 
        EMP_DETAILS TYPE_EMP_DETAILS;
    BEGIN
        SELECT EMPLOYEE_ID,FIRST_NAME,SALARY INTO EMP_DETAILS
        FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=P_EMPLOYEE_ID;
        
        RETURN EMP_DETAILS;
    END;
END;   

DECLARE
    EMP_DETAILS EMP_UTILS.TYPE_EMP_DETAILS; 
BEGIN
    EMP_DETAILS := EMP_UTILS.GET_EMP_DETAILS_BY_ID(101);
    DBMS_OUTPUT.PUT_LINE(EMP_DETAILS.EMPLOYEE_NAME||'---'||EMP_DETAILS.SALARY);
END;
