CREATE OR REPLACE PROCEDURE PRINT_EMPS(P_DEPARTMENT_ID HR.EMPLOYEES.DEPARTMENT_ID%TYPE)
AS
    CURSOR CUR_EMPS IS SELECT FIRST_NAME,SALARY FROM HR.EMPLOYEES WHERE DEPARTMENT_ID=P_DEPARTMENT_ID; 
    V_FIRST_NAME HR.EMPLOYEES.FIRST_NAME%TYPE;
    V_SALARY HR.EMPLOYEES.SALARY%TYPE;
    V_EMP_ROW HR.EMPLOYEES%ROWTYPE;
BEGIN
    OPEN CUR_EMPS;
    LOOP
        FETCH CUR_EMPS INTO V_FIRST_NAME,V_SALARY;
        EXIT WHEN CUR_EMPS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_FIRST_NAME||'.'||V_SALARY);
    END LOOP;
END;

EXEC PRINT_EMPS(100);


CREATE OR REPLACE PROCEDURE PRINT_ENTIRE_EMPS(P_DEPARTMENT_ID HR.EMPLOYEES.DEPARTMENT_ID%TYPE)
AS
    CURSOR CUR_EMPS IS SELECT * FROM HR.EMPLOYEES WHERE DEPARTMENT_ID=P_DEPARTMENT_ID; 
    V_EMP_ROW HR.EMPLOYEES%ROWTYPE;
BEGIN
    OPEN CUR_EMPS;
    LOOP
        FETCH CUR_EMPS INTO V_EMP_ROW;
        EXIT WHEN CUR_EMPS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_EMP_ROW.FIRST_NAME||'------'||V_EMP_ROW.SALARY||'------'||V_EMP_ROW.DEPARTMENT_ID);
    END LOOP;
END;

EXEC PRINT_ENTIRE_EMPS(100);

CREATE OR REPLACE PROCEDURE PRINT_CUSTOM_EMPS(P_DEPARTMENT_ID HR.EMPLOYEES.DEPARTMENT_ID%TYPE)
AS
    CURSOR CUR_EMPS IS SELECT FIRST_NAME,SALARY,MANAGER_ID FROM HR.EMPLOYEES WHERE DEPARTMENT_ID=P_DEPARTMENT_ID; 
    TYPE EMP_TYP IS RECORD
    (
        EMPNAME  HR.EMPLOYEES.FIRST_NAME%TYPE,
        EMPSALARY HR.EMPLOYEES.SALARY%TYPE,
        MANAGER HR.EMPLOYEES.MANAGER_ID%TYPE
    );
    
    V_EMP_ROW EMP_TYP;
    
BEGIN
    OPEN CUR_EMPS;
    LOOP
        FETCH CUR_EMPS INTO V_EMP_ROW;
        EXIT WHEN CUR_EMPS%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_EMP_ROW.EMPNAME||'------'||V_EMP_ROW.EMPSALARY||'------'||V_EMP_ROW.MANAGER);
    END LOOP;
    CLOSE CUR_EMPS;
END;



CREATE OR REPLACE PROCEDURE PRINT_CUSTOM_EMPS_WITH_FORLOOP(P_DEPARTMENT_ID HR.EMPLOYEES.DEPARTMENT_ID%TYPE)
AS
    CURSOR CUR_EMPS IS SELECT FIRST_NAME EMPNAME,SALARY,MANAGER_ID FROM HR.EMPLOYEES WHERE DEPARTMENT_ID=P_DEPARTMENT_ID; 
BEGIN
    FOR emp IN CUR_EMPS LOOP
        DBMS_OUTPUT.PUT_LINE(emp.EMPNAME||'------'||emp.SALARY||'------'||emp.MANAGER_ID);
    END LOOP;
END;

EXEC PRINT_CUSTOM_EMPS_WITH_FORLOOP(100);



CREATE OR REPLACE PROCEDURE PRINT_EMPS_WITH_CURSOR_PARAMS
AS
    CURSOR DEPTS IS SELECT DEPARTMENT_ID FROM HR.EMPLOYEES GROUP BY DEPARTMENT_ID HAVING COUNT(EMPLOYEE_ID) > 5;
    
    CURSOR CUR_EMPS(CP_DEPARTMENT_ID HR.EMPLOYEES.DEPARTMENT_ID%TYPE) IS SELECT FIRST_NAME EMPNAME,SALARY,MANAGER_ID FROM HR.EMPLOYEES WHERE DEPARTMENT_ID=CP_DEPARTMENT_ID; 
BEGIN
    FOR DEPTID IN DEPTS LOOP
        FOR emp IN CUR_EMPS(DEPTID.DEPARTMENT_ID) LOOP
            DBMS_OUTPUT.PUT_LINE(emp.EMPNAME||'------'||emp.SALARY||'------'||emp.MANAGER_ID);
        END LOOP;
    END LOOP;
END;

EXEC PRINT_EMPS_WITH_CURSOR_PARAMS


CREATE OR REPLACE PROCEDURE PRINT_NAMES
AS
   TYPE CUR_NAME_TYPE IS REF CURSOR;
   CUR_NAME CUR_NAME_TYPE;
   V_NAME VARCHAR(128);
BEGIN
   OPEN CUR_NAME FOR SELECT FIRST_NAME AS NAME FROM HR.EMPLOYEES;
   LOOP
        FETCH CUR_NAME INTO V_NAME;
        EXIT WHEN CUR_NAME%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_NAME);
   END LOOP;
   CLOSE CUR_NAME;
   
   
   OPEN CUR_NAME FOR SELECT DEPARTMENT_NAME FROM HR.DEPARTMENTS;
   LOOP
        FETCH CUR_NAME INTO V_NAME;
        EXIT WHEN CUR_NAME%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(V_NAME);
   END LOOP;
END;

EXEC PRINT_NAMES;

